### ISSUE TITLE
The browser (or proxy) sent a request that this server could not understand.

### ISSUE THREAD

**Issue by MAGICCC** [UiP9AV6Y/dockerfiles#1]
Hi, 
I am using your docker containers for my powerdns setup, since I am moving away from bind. PDNS and PDNS-Admin have separated postgresql databases and when I try to add domains in the Admininterface I sometimes get the error stacktrace below. Do note I access the webpage directly over the host where the container is running thus no proxies involved

```
app_1               | [uwsgi-body-read] Timeout reading 4517 bytes. Content-Length: 4517 consumed: 0 left: 4517
app_1               | [pid: 25|app: 0|req: 727/2280] 10.233.85.4 () {42 vars in 1042 bytes} [Tue Oct 23 21:17:20 2018] POST /domain/kthx.at/apply => generated 69 bytes in 4009 msecs (HTTP/1.1 500) 2 headers in 90 bytes (3 switches on core 1)
app_1               | Traceback (most recent call last):
app_1               |   File "./app/views.py", line 606, in record_apply
app_1               |     pdata = request.data
app_1               |   File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
app_1               |     return getattr(self._get_current_object(), name)
app_1               |   File "/usr/lib/python2.7/site-packages/werkzeug/utils.py", line 73, in __get__
app_1               |     value = self.func(obj)
app_1               |   File "/usr/lib/python2.7/site-packages/werkzeug/wrappers.py", line 483, in data
app_1               |     return self.get_data(parse_form_data=True)
app_1               |   File "/usr/lib/python2.7/site-packages/werkzeug/wrappers.py", line 514, in get_data
app_1               |     rv = self.stream.read()
app_1               |   File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 1305, in read
app_1               |     return self.on_disconnect()
app_1               |   File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 1275, in on_disconnect
app_1               |     raise ClientDisconnected()
app_1               | ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

**Comment by UiP9AV6Y** [comment]
you might want to raise this issue with the [upstream project](https://github.com/thomasDOTwtf/PowerDNS-Admin); this project is merely packaging the application as a docker image.
