### ISSUE TITLE
Sqlite DatabaseAlreadyControlledError

### ISSUE THREAD

**Issue by inwaar** [UiP9AV6Y/dockerfiles#3]
Everything works fine on the first time container is created but if it's restarted the following error is arises:

```
INFO: Wait for database server,
Traceback (most recent call last):,
  File "create_db.py", line 95, in <module>,
    start(),
  File "create_db.py", line 19, in start,
    init_records(),
  File "create_db.py", line 85, in init_records,
    commit_version_control(db_commit),
  File "create_db.py", line 90, in commit_version_control,
    api.version_control(SQLALCHEMY_DATABASE_URI, SQLALCHEMY_MIGRATE_REPO),
  File "</usr/lib/python2.7/site-packages/decorator.pyc:decorator-gen-8>", line 2, in version_control,
  File "/usr/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 160, in with_engine,
    return f(*a, **kw),
  File "/usr/lib/python2.7/site-packages/migrate/versioning/api.py", line 250, in version_control,
    ControlledSchema.create(engine, repository, version),
  File "/usr/lib/python2.7/site-packages/migrate/versioning/schema.py", line 141, in create,
    table = cls._create_table_version(engine, repository, version),
  File "/usr/lib/python2.7/site-packages/migrate/versioning/schema.py", line 189, in _create_table_version,
    raise exceptions.DatabaseAlreadyControlledError,
migrate.exceptions.DatabaseAlreadyControlledError,

**Comment by UiP9AV6Y** [comment]
i cannot reproduce the issue. what database are you using for storage (sqlite, postgres, ...) and how are you deploying the image (docker-compose, kubernetes, ...)
