### ISSUE TITLE
[BUG] PowerDNS-Admin MySQL - Unable to upload profile picture

### ISSUE THREAD

**Issue by imxari** [UiP9AV6Y/dockerfiles#4]
Any attempt at uploading a profile picture results in the error:
```
[2019-07-10 20:03:17,358] ERROR in app: Exception on /user/profile [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "./app/views.py", line 924, in user_profile
    file.save(os.path.join(app.config['UPLOAD_DIR'], 'avatar', save_file_name))
  File "/usr/lib/python2.7/site-packages/werkzeug/datastructures.py", line 2799, in save
    dst = open(dst, "wb")
IOError: [Errno 2] No such file or directory: u'/app/uploads/avatar/lkeenan.png'
```
Docker Version:
```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
```

Docker-Compose Version:
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Comment by imxari** [comment]
bump
